[build]
  command = "echo 'PWA build complete'"
  publish = "."

[build.environment]
  NODE_VERSION = "18"
  PYTHON_VERSION = ""

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200